### ISSUE TITLE
[MJAR-269] Add Skip Property to Skip Plugin Execution

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-jar-plugin#418]
**[Brian Wyka](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianwyka)** opened **[MJAR-269](https://issues.apache.org/jira/browse/MJAR-269?redirect=false)** and commented

Expose plugin configuration as well as a user property to allow the plugin execution to be skipped.

 

There are occasions when we do not always want to run jar plugin.

 

Example:

In a build pipeline, we run different phases in different stages

 
1. Run install in isolation (we need jar here)
2. Run deploy in isolation (we don't need jar again - so need a way to skip)

 

Currently there is only a hack to do this, by overriding the **default-jar** execution of the plugin and setting the phase to a user property, and then overriding that to a non-existent phase, to keep it from being attached to the maven lifecycle.

---

**Remote Links:**
- [GitHub Pull Request #7
](https://github.com/apache/maven-jar-plugin/pull/7)

**Comment by jira-importer** [comment]
**[Brian Wyka](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianwyka)** commented

[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte), both of those plugins already have skip properties enabled:
* maven-compiler-plugin: https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#skipMain
* maven-resources-plgin: https://maven.apache.org/plugins/maven-resources-plugin/resources-mojo.html#skip

Calling **deploy:deploy** is a partial solution in this case for sure.  However, it prevents custom implementations of a pom which tie into the **deploy** phase from executing in this case, so not optimal or ideal, unfortunately.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

I didn't expect these parameters to exist, but it doesn't change my opinion. The description is quite clear, it is no recommended and that's for me a code smell.
I won't introduce workarounds if I know we can do better (because once workarounds exist it is very hard to remove them).

**Comment by jira-importer** [comment]
**[Brian Wyka](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianwyka)** commented

Any ideas other than the one mentioned in the issue description on how to acccomplish this?  Honestly, to me, the "solution" in the issue description is more of a hack than anything else.

Trying to brainstorm how we can do this better, but not seeing a way since I still want other plugins to be able to tie into the deploy phase and to not be skipped as they would be by calling **deploy:deploy** in isolation.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Maven offers several options you can write by yourself: plugins, extensions and custom lifecycles. Since you want to call several plugins bound to the same phase, a custom lifecycle might be an option. These aren't well described, though.

**Comment by norrisjeremy** [comment]
For example, the most common answer on [Stackoverflow](https://stackoverflow.com/questions/2188746/what-is-the-best-way-to-avoid-maven-jar) is a recommendation to set the phase for the `default-jar` execution to a nonexistent value (such as `none`).

So instead of letting users simply specify `mvn -Dmaven.jar.skip=true ...` as so many other plugins do, users instead end up having to add a semi-convoluted config like this in order to support conditionalized execution via the command line using `mvn -Djar.phase=none ...`:
```xml
<properties>
  <jar.phase>package</jar.phase>
</properties>
<build>
  <plugins>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-jar-plugin</artifactId>
      <executions>
        <execution>
          <id>default-jar</id>
          <!-- allow override since this plugin doesn't have a property to skip execution -->
          <phase>${jar.phase}</phase>
        </execution>
      </executions>
    </plugin>
  </plugins>
<build>
```
